%% Nodges - Branch-Graph des Haupt-Repos Banixx/Nodges (vereinfacht)
gitGraph
    commit id: "0.78 a59b3bf"
    commit id: "0.81"
    commit id: "0.82"
    commit id: "0.89"
    commit id: "0.90"
    commit id: "0.92.19"
    commit id: "Post Transfer"
    commit id: "0.93"
    branch feature/multi-build
    commit id: "0.101.3"
    checkout main
    commit id: "0.101.2"
    merge feature/multi-build id: "PR #1"
    commit id: "0.101.5"
    commit id: "0.102.x"
    merge feature/multi-build id: "0.102.4"
    commit id: "0.103 (1d177e5)"
    branch pi
    commit id: "0.103.1 von Pi"
    commit id: "104"
    commit id: "0.105.0"
    commit id: "0.105.1 (d4391c0)"
    checkout main
    commit id: "476bf6c (chore)"
