@echo off
echo Starte Nodges Entwicklungsserver...
start cmd /k "npm run dev"
echo Warte auf Server-Initialisierung...
timeout /t 2 >nul
echo Oeffne Webseite im Browser...
start http://localhost:5173/
