graph TD
    VisualMappingPanel --> UIManager
    UIManager --> App
    App --> VisualMappingEngine
    App --> StateManager
    App --> NodeManager
    App --> EdgeObjectsManager
    NodeManager --> VisualMappingEngine
    EdgeObjectsManager --> VisualMappingEngine
    VisualMappingEngine --> Normalisierung
    Normalisierung --> VisuelleEigenschaften
    VisuelleEigenschaften --> ThreeJSMeshes
