export const STATE_KEY_TO_CATEGORIES: Record<string, string[]> = {
    graphData: ['data'],
    hoveredObject: ['interaction'],
    selectedObject: ['interaction'],
    selectedObjects: ['interaction'],
    isBoxSelecting: ['interaction'],
    highlightedObjects: ['visual'],
    glowIntensity: ['visual'],
    glowDirection: ['visual'],
    tooltipVisible: ['ui'],
    tooltipContent: ['ui'],
    tooltipPosition: ['ui'],
    infoPanelVisible: ['ui'],
    infoPanelCollapsed: ['ui'],
    highlightEffectsEnabled: ['visual'],
    isInteractionEnabled: ['system'],
    currentTool: ['system'],
    edgeThickness: ['edge'],
    edgeTubularSegments: ['edge'],
    edgeRadialSegments: ['edge'],
    edgeCurveFactor: ['edge'],
    edgePulseSpeed: ['edge'],
    highlightThickness: ['edge'],
    selectionThickness: ['edge'],
    layoutEnabled: ['layout'],
    backgroundColor: ['environment'],
    ambientLightIntensity: ['environment'],
    directionalLightIntensity: ['environment'],
    showLabelsAlways: ['view'],
    showLabelsOnHover: ['view'],
    activeColorScheme: ['view'],
    devPowerPreference: ['dev'],
    devPixelRatio: ['dev'],
    devFpsLimit: ['dev'],
    _triggerRendererRebuild: ['dev']
};

export const STATE_CATEGORIES = {
    DEFAULT: 'default',
    DATA: 'data',
    INTERACTION: 'interaction',
    VISUAL: 'visual',
    UI: 'ui',
    SYSTEM: 'system',
    EDGE: 'edge',
    LAYOUT: 'layout',
    ENVIRONMENT: 'environment',
    VIEW: 'view',
    DEV: 'dev'
} as const;

export type StateCategory = keyof typeof STATE_CATEGORIES;